#!/bin/bash

function install_bashfile {
    local srcfile="$1" destfile=".$(basename "$bashfile")"
    ln -s "$srcfile" "$destfile" && echo "$destfile -> $srcfile"
}

function install_bashfiles {
    local bashfile
    for bashfile in $(ls $(dirname "$0")/bash*); do
        install_bashfile $bashfile
    done
}

install_bashfiles